name: dipgnnome_cpu
channels:
  - conda-forge
  - pytorch
  - bioconda

dependencies:
  # Python version
  - python=3.9
  
  # Core scientific computing
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  
  # Machine learning and deep learning (CPU versions)
  - pytorch>=1.12.0
  - torchvision>=0.13.0
  - torchaudio>=0.12.0
  - cpuonly  # Ensures CPU-only PyTorch installation
  
  # Graph processing
  - networkx>=2.6.0
  
  # Bioinformatics
  - biopython>=1.79
  - edlib>=1.3.9
  - pyliftover>=0.4
  
  # Utilities
  - tqdm>=4.62.0
  - pyyaml>=6.0
  
  # Experiment tracking
  - wandb>=0.12.0
  
  # System tools
  - git
  - make
  - gcc_linux-64  # For Linux
  - gxx_linux-64  # For Linux
  - clang_osx-64  # For macOS
  - clangxx_osx-64  # For macOS
  
  # Pip packages (for packages not available in conda)
  - pip
  - pip:
    - dgl>=1.0.0  # Deep Graph Library
    - argparse  # Usually included in Python 3.2+

# Environment variables for CPU optimization
variables:
  OMP_NUM_THREADS: "4"  # Adjust based on your CPU cores
  MKL_NUM_THREADS: "4"  # For Intel MKL optimization
