paths:
  sample_profile: hg002hifi
  pbsim_path: /home/schmitzmf/pbsim3
  hifiasm_path: /home/schmitzmf/hifiasm_025/
  hifiasm_dump: /home/schmitzmf/scratch/dumps/hifiasm_dump_1
  yak_path: /home/schmitzmf/yak
  centromere_coords: /home/schmitzmf/diploid_gnnome/data/centromere_coordinates_same_len.yml
gen_config:
  depth: 20
  threads: 32
  assembler: hifiasm
  diploid: True
  real: False
gen_steps:
  sample_reads: False
  create_graphs: True
  parse_gfa: False
  full_2_utg: False
  create_yak: False
  diploid_features: False
  ground_truth: True
  ml_graphs: True

training:
  i002c_v04.multi_21: 32

validation:
  i002c_v04.multi_21: 4
