hg002:
  mat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/hg002_v101/mat.yak'
  pat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/hg002_v101/pat.yak'
  full_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/hg002_v101/hg002v1.0.1.fasta'
  mat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/hg002_v101/hg002v1.0.1_MATERNAL.fasta'
  pat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/hg002_v101/hg002v1.0.1_PATERNAL.fasta'
  chr_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/hg002_v101/chromosomes'
  cent_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/hg002_v101/centromeres'

mgorgor:
  mat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mGorGor1_v2/mat.yak'
  pat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mGorGor1_v2/pat.yak'
  mat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mGorGor1_v2/mGorGor1_Mat.fasta'
  pat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mGorGor1_v2/mGorGor1_Pat.fasta'
  full_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mGorGor1_v2/mGorGor1_v2.0.fasta'
  chr_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mGorGor1_v2/chromosomes'
  cent_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mGorGor1_v2/centromeres'

mpanpan:
  mat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPanPan1_v2/mat.yak'
  pat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPanPan1_v2/pat.yak'
  mat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPanPan1_v2/mPanPan1_Mat.fasta'
  pat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPanPan1_v2/mPanPan1_Pat.fasta'
  full_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPanPan1_v2/mPanPan1_v2.0.fasta'
  chr_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPanPan1_v2/chromosomes'
  cent_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPanPan1_v2/centromeres'

mpantro:
  mat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPanTro3_v2/mat.yak'
  pat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPanTro3_v2/pat.yak'
  mat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPanTro3_v2/mPanTro3_hap2.fasta'
  pat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPanTro3_v2/mPanTro3_hap1.fasta'
  full_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPanTro3_v2/mPanTro3_v2.0.fasta'
  chr_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPanTro3_v2/chromosomes'
  cent_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPanTro3_v2/centromeres'

msymsyn:
  mat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mSymSyn1_v2/mat.yak'
  pat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mSymSyn1_v2/pat.yak'
  mat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mSymSyn1_v2/mSymSyn1_hap2.fasta'
  pat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mSymSyn1_v2/mSymSyn1_hap1.fasta'
  full_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mSymSyn1_v2/mSymSyn1_v2.0.fasta'
  chr_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mSymSyn1_v2/chromosomes'
  cent_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mSymSyn1_v2/centromeres'

mponabe:
  mat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPonAbe1_v2/mat.yak'
  pat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPonAbe1_v2/pat.yak'
  mat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPonAbe1_v2/mPonAbe1_hap2.fasta'
  pat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPonAbe1_v2/mPonAbe1_hap1.fasta'
  full_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPonAbe1_v2/mPonAbe1_v2.0.fasta'
  chr_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPonAbe1_v2/chromosomes'
  cent_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPonAbe1_v2/centromeres'

mponpyg:
  mat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPonPyg2_v2/mat.yak'
  pat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPonPyg2_v2/pat.yak'
  mat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPonPyg2_v2/mPonPyg2_hap1.fasta'
  pat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPonPyg2_v2/mPonPyg2_hap2.fasta'
  full_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPonPyg2_v2/mPonPyg2_v2.0.fasta'
  chr_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPonPyg2_v2/chromosomes'
  cent_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/mPonPyg2_v2/centromeres'


i002c:
  mat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/i002c_v04/mat.yak'
  pat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/i002c_v04/pat.yak'
  full_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/i002c_v04/i002c_v04.fasta'
  mat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/i002c_v04/I002C_v0.4_MATERNAL.fasta'
  pat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/i002c_v04/I002C_v0.4_PATERNAL.fasta'
  chr_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/i002c_v04/chromosomes'
  cent_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/i002c_v04/centromeres'

chinese_tree:
  full_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/chinese_tree/chinese_tree.fasta'
  chr_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/chinese_tree/chromosomes'
  cent_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/chinese_tree/centromeres'
  mat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/chinese_tree/chinese_tree_M.fasta'
  pat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/chinese_tree/chinese_tree_P.fasta'
  mat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/chinese_tree/mat.yak'
  pat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/chinese_tree/pat.yak'

eucalyptus:
  full_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/eucalyptus/eucalyptus.fasta'
  chr_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/eucalyptus/chromosomes'
  cent_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/eucalyptus/centromeres'
  mat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/eucalyptus/eucalyptus_M.fasta'
  pat_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/eucalyptus/eucalyptus_P.fasta'
  mat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/eucalyptus/mat.yak'
  pat_yak: '/mnt/sod2-project/csb4/wgs/martin/genome_references/eucalyptus/pat.yak'

arabidopsis:
  full_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/arabidopsis/GWHBDNP00000000.1.genome.fasta'
  chr_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/arabidopsis/chromosomes'
mouse:
  full_ref: '/mnt/sod2-project/csb4/wgs/lovro/gnnome_assembly/references/mus_musculus/mmusculus_GRCm39.fna'
chicken:
  full_ref: '/mnt/sod2-project/csb4/wgs/lovro/gnnome_assembly/references/bGalGal1/maternal/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.fna'
chm13:
  full_ref: '/mnt/sod2-project/csb4/wgs/lovro/gnnome_assembly/references/CHM13/chm13.draft_v1.1.fasta'

arabidopsis_col_cc:
  full_ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/arabidopsis_col_cc/GCA_028009825.1_Col-CC_genomic.fna'
  chr_refs: '/mnt/sod2-project/csb4/wgs/martin/genome_references/arabidopsis_col_cc/chromosomes'
mouse:
  full_ref: '/mnt/sod2-project/csb4/wgs/lovro/gnnome_assembly/references/mus_musculus/mmusculus_GRCm39.fna'
chicken:
  full_ref: '/mnt/sod2-project/csb4/wgs/lovro/gnnome_assembly/references/bGalGal1/maternal/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.fna'
chm13:
  full_ref: '/mnt/sod2-project/csb4/wgs/lovro/gnnome_assembly/references/CHM13/chm13.draft_v1.1.fasta'
