paths:
  sample_profile: hg002hifi
  pbsim_path: /home/schmitzmf/pbsim3
  hifiasm_path: /home/schmitzmf/hifiasm_025/
  hifiasm_dump: /home/schmitzmf/scratch/dumps/hifiasm_dump_1
  yak_path: /home/schmitzmf/yak
  centromere_coords: /home/schmitzmf/diploid_gnnome/data/centromere_coordinates_same_len.yml
gen_config:
  depth: 20
  threads: 32
  assembler: hifiasm
  diploid: True
  real: True
gen_steps:
  sample_reads: False
  create_graphs: True
  parse_gfa: True
  full_2_utg: True
  create_yak: True
  diploid_features: True
  ground_truth: True
  ml_graphs: True

training:
  mGorGor1_v2.full: 1

validation: